\documentclass[11pt,a4paper]{article}
\usepackage{fullpage}

\begin{document}

\section{Data loading and processing}

First, I source the code for the functions.

<<loadmdsfuns>>=
source("mds.R")
@ 

<<loadlibraries>>=
require(rjags)
#require(shapes)
require(plotrix)
#require(seqinr)
@ 

I now define a new matplot function (from plotrix) that makes a prettier plot. I can't remember exactly what I changed, but it does the job.

<<defmymatplot>>=
mymatplot <- function (x, redrange = c(0, 1), greenrange = c(0, 1), bluerange = c(0, 
    1), extremes = NA, cellcolors = NA, show.legend = FALSE, 
    nslices = 10, xlab = "Column", ylab = "Row", do.hex = FALSE, 
    axes = TRUE, show.values = FALSE, vcol = "white", vcex = 1, 
    border = "black", na.color = NA, values = NA, ...) 
{
    if (is.matrix(x) || is.data.frame(x)) {
        xdim <- dim(x)
        if (is.data.frame(x)) 
            x <- unlist(x)
        else x <- as.vector(x)
        oldpar <- par("xaxs", "yaxs", "xpd", "mar")
        par(xaxs = "i", yaxs = "i")
        if (do.hex) 
            par(mar = c(5, 4, 4, 4))
        plot(c(0, xdim[2]), c(0, xdim[1]), xlab = xlab, ylab = ylab, 
            type = "n", axes = FALSE, ...)
        oldpar$usr <- par("usr")
        if (!do.hex) {
            box()
            pos <- 0
        }
        else pos <- -0.3
        if (axes) {
            xticks <- pretty(0:xdim[2])[-1]
            axis(1, at = xticks - 0.5, labels = xticks, pos = pos)
            yticks <- pretty(0:xdim[1])[-1]
            axis(2, at = xdim[1] - yticks + 0.5, yticks)
        }
        if (all(is.na(cellcolors))) 
            cellcolors <- color.scale(x, redrange, greenrange, 
                bluerange, extremes, na.color)
        if (do.hex) {
            par(xpd = TRUE)
            offset <- 0
            if (length(border) < xdim[1] * xdim[2]) 
                border <- rep(border, length.out = xdim[1] * 
                  xdim[2])
            for (row in 1:xdim[1]) {
                for (column in 0:(xdim[2] - 1)) {
                  hexagon(column + offset, xdim[1] - row, col = cellcolors[row + 
                    xdim[1] * column], border = border[row + 
                    xdim[1] * column])
                  if (show.values){
                    if(is.na(values)){
                    text(column + offset + 0.5, xdim[1] - row + 
                      0.5, x[row + column * xdim[1]], col = vcol, 
                      cex = vcex)
                  }
                    else{
                      text(column + offset + 0.5, xdim[1] - row + 
                      0.5, values, col = vcol, 
                      cex = vcex)
                    }
                  }
                }
                offset <- ifelse(offset, 0, 0.5)
            }
            par(xpd = FALSE)
        }
        else {
            rect(sort(rep((1:xdim[2]) - 1, xdim[1])), rep(seq(xdim[1] - 
                1, 0, by = -1), xdim[2]), sort(rep(1:xdim[2], 
                xdim[1])), rep(seq(xdim[1], 1, by = -1), xdim[2]), 
                col = cellcolors, border = border)
            if (show.values){
              if(is.na(values)){
                text(sort(rep((1:xdim[2]) - 0.5, xdim[1])), rep(seq(xdim[1] - 
                  0.5, 0, by = -1), xdim[2]), round(x, show.values), 
                  col = vcol, cex = vcex)
              }
              else{
                text(sort(rep((1:xdim[2]) - 0.5, xdim[1])), rep(seq(xdim[1] - 
                  0.5, 0, by = -1), xdim[2]), values, 
                  col = vcol, cex = vcex)
              }
              }
        }
        naxs <- which(is.na(x))
        xy <- par("usr")
        plot.din <- par("din")
        plot.pin <- par("pin")
        bottom.gap <- (xy[3] - xy[4]) * (plot.din[2] - plot.pin[2])/(2 * 
            plot.pin[2])
        grx1 <- xy[1]
        gry1 <- bottom.gap * 0.95
        grx2 <- xy[1] + (xy[2] - xy[1])/4
        gry2 <- bottom.gap * 0.8
        if (length(cellcolors) > 1) {
            colmat <- col2rgb(c(cellcolors[which.min(x)], cellcolors[which.max(x)]))
            redrange <- colmat[1, ]/255
            greenrange <- colmat[2, ]/255
            bluerange <- colmat[3, ]/255
        }
        rect.col <- color.scale(1:nslices, redrange, greenrange, 
            bluerange)
        if (show.legend) 
            color.legend(grx1, gry1, grx2, gry2, round(range(x, 
                na.rm = TRUE), show.legend), rect.col = rect.col)
        par(oldpar)
    }
    else cat("x must be a data frame or matrix\n")
}
@ 

I now read in the data.

<<readhivdata>>=
hivdata <- read.table("kircherr.neut.txt",header=T,row.names=NULL)
hiv.df <- hivdata[,2:17]
hiv <- as.matrix(hiv.df)
dimnames(hiv)[[1]] <- as.character(hivdata[,1])
hiv.names <- row.names(hiv)
sera.names <- dimnames(hiv)[[2]]
hiv.patients <- unlist(lapply(strsplit(hiv.names,".",fixed=TRUE),"[",1))
nrow <- 60
ncol <- 16
@ 

I now generate the files needed for the matrix plot.

<<fig=TRUE>>=
hivfigmat <- readneut(hiv,logtransform=FALSE)$d
hmmat <- log2(hivfigmat[1:nrow,])
hm <- heatmap(hmmat)
hivfigmat2 <- hivfigmat[,hm$colInd]
hiv.names2 <- hiv.names#hiv.names[c(hm$rowInd,seq(24,28))]
sera.names2 <- sera.names[hm$colInd]
vals <- hiv[,hm$colInd]
vals <- gsub(" ","",as.vector(apply(vals,2,as.character)))
vals <- unlist(lapply(strsplit(vals,".",fixed=TRUE),"[",1))
matcols <- heat.colors(6)
x <- hivfigmat2
tabsize <- dim(x)
cellcol<-matrix(rep("gray",tabsize[1]*tabsize[2]),nrow=tabsize[1])
cellcol[x>10&x<50]<- matcols[5]
cellcol[x>40&x<100] <- matcols[4]
cellcol[x>=100&x<200] <- matcols[3]
cellcol[x>=200&x<500] <- matcols[2]
cellcol[x>=500&x<1000] <- matcols[1]
cellcol[x>=1000] <- "black"
cellcol[is.na(x)] <- "white"
pdf("kircherrtable.pdf",width=10,height=12)
par(mar=c(5,7,5,5))
mymatplot(x,cellcolors=cellcol,show.legend=FALSE,show.values=TRUE,border=TRUE,axes=F,xlab="",ylab="",values=vals)
axis(1,at=seq(1,ncol)-0.5,labels=gsub("X","",sera.names2),las=2,cex=0.6)
axis(2,at=seq(nrow,1,by=-1)-0.5,labels=hiv.names2,las=1,cex=0.6)
mtext("Sera",3,line=1,cex=1.0,font=2)
mtext("Virus",4,line=1,cex=1.0,font=2)
dev.off()
@ 

I now prepare the data for analysis.

<<prepdata>>=
hivmat <- readneut(hiv[1:nrow,],logtransform=TRUE)
hivdat <- prepdata(hivmat)
hivdat.orig <- hivdat # Handy as JAGS overwrites the data passed to it
@ 


I need to exclude the high values. I now set up the censoring and the autologous (reference) virus/sera combinations.

I now set up the censoring and the autologous (reference) virus/sera combinations. As there are ND measurements, I have to normalize using a special function.

<<>>=
mymax <- function(x){
  x <- na.omit(x)
  max(x)
}
@ 

<<setupdata>>=
eps <- 0.00001
hivdat <- prepdata(hivmat)
#hivdat$d[hivdat$d>log2(1000)] <- NA # Exclude the high values, which are probably outliers
hivdat.max <- rep(apply(hivmat$d,2,mymax),each=dim(hivmat$d)[1])
hivdat$d <- -(hivdat$d-hivdat.max)
hivdat.nocen <- hivdat[c(-2,-3)] # This removes the variables associated with censoring
hivdat$lod[,1] <- rep(-eps,hivdat$M) # This seems odd as the maximum is zero, which differs for different sera. Hence, the 'upper' lod is actually the lower lod, and the upper lod differs for everyone
hivdat$lod[,2] <- hivdat.max-log2(10)+eps
hivdat$lod[is.na(hivdat$lod[,1]),1] <- min(na.omit(hivdat$lod))
hivdat$lod[is.na(hivdat$lod[,2]),2] <- max(na.omit(hivdat$lod))
hivdat$cen[hivdat$cen==0] <- 2
hivdat.orig <- hivdat
hivdat.dinit <- hivdat.max
hivdat.dinit[hivdat$cen==1] <- NA
hivdat.inits <- list(d=hivdat.dinit,RNG.name="base::Mersenne-Twister",.RNG.seed=1)
@ 


\section{Model fitting with JAGS}

I can now fit BMDS to the HIV data. I need to check that all the indexing is working OK.

First, with no censoring.

<<hivnocenbmds>>=
hiv.nocen.bmds <- jags.model('bmds.nonorm.nocen.bug',data=hivdat.nocen,n.chains=1,n.adapt=1000)
update(hiv.nocen.bmds,n.iter=1000)
hiv.nocen.bmds.samples <- jags.samples(hiv.nocen.bmds,variable.names=c("delta","x1","x2","y1","y2","tau.d","tau.x0","d"),n.iter=10000,thin=10)
hiv.nocen.bmds.samples.mcmclist <- lapply(hiv.nocen.bmds.samples,as.mcmc.list) 
@ 

<<hivbmds>>=
#dinit <- as.double(hiv.nocen.bmds.samples.mcmclist$d[1000,][[1]])
dinit <- rep(10,length(hivdat$d))
dinit[hivdat$cen==1] <- NA
hiv.bmds <- jags.model('bmds.nonorm.bug',data=hivdat,inits=list(d=dinit),n.chains=1,n.adapt=1000)
update(hiv.bmds,n.iter=1000)
hiv.bmds.samples <- jags.samples(hiv.bmds,variable.names=c("delta","x1","x2","y1","y2","tau.d","tau.x0","d"),n.iter=100000,thin=100)
hiv.bmds.samples.mcmclist <- lapply(hiv.bmds.samples,as.mcmc.list) 
@ 

Need to monitor deviance as well, ideally, as another check on convergence. I probably also need to include a uniform prior.

I fit BPCA; need to check this.

<<hivbpca>>=
hivdat.bpca <- prepdata(hivmat) # prepare data
hivdat.bpca$lod[,2] <- hivdat.max+eps # this is fine
hivdat.bpca$lod[,1] <- rep(log2(10)-eps,hivdat.bpca$M)
#hivdat.bpca$lod[(!is.na(hivdat.bpca$d))&(hivdat.bpca$d<log2(40)),1] <- (hivdat.bpca$d-eps)[!is.na(hivdat.bpca$d)&(hivdat.bpca$d<log2(20))]
# Due to censoring, we have to pass initial values
dinit <- rep(log2(10)-2*eps,length(hivdat.bpca$d))
dinit[hivdat.bpca$cen==1] <- NA # don't need initials for uncensored measurements
dinit[seq(1,length(hivdat.bpca$d))[is.na(hivdat.bpca$d)&(hivdat.bpca$cen==1)]] <- log2(10) # ND measurements, initialized at LOD
hiv.bpca <- jags.model('bpca.bug',data=hivdat.bpca,inits=list(d=dinit,.RNG.name="base::Mersenne-Twister",.RNG.seed=1),n.chains=1,n.adapt=1000)
update(hiv.bpca,n.iter=1000)
hiv.bpca.samples <- jags.samples(hiv.bpca,variable.names=c("mu","x","W","tau.y","tau.W"),n.iter=10000,thin=10)
hiv.bpca.samples.mcmclist <- lapply(hiv.bpca.samples,as.mcmc.list)
@ 

\section{Output processing}

I now extract the coordinates and align using unweighted and weighted GPA.

<<mapdatabmds,fig=TRUE>>=
hiv.nocen.bmds.xmat <- mapdata.mds(hivdat.orig,hiv.nocen.bmds.samples.mcmclist,seq(1,1000,by=10))
require(shapes)
hiv.nocen.bmds.xmat.gpa <- procGPA(hiv.nocen.bmds.xmat)
hiv.nocen.bmds.xmat.wgpa <- procWGPA(hiv.nocen.bmds.xmat,fixcovmatrix=FALSE,initial="Identity",maxiterations=100,scale=FALSE,prior="Exponential",diagonal=TRUE,sampleweights="Equal")
@  

<<mapdatabmds,fig=TRUE>>=
hiv.bmds.xmat <- mapdata.mds(hivdat.orig,hiv.bmds.samples.mcmclist,seq(1,1000,by=10))
hiv.bmds.xmat.gpa <- procGPA(hiv.bmds.xmat)
hiv.bmds.xmat.wgpa <- procWGPA(hiv.bmds.xmat,fixcovmatrix=FALSE,initial="Identity",maxiterations=100,scale=FALSE,prior="Exponential",diagonal=TRUE,sampleweights="Equal")
@  

I obtain ordinations for BPCA.

<<mapdatabpca,fig=TRUE>>=
hiv.bpca.xmat <- mapdata.pca(hivdat.orig,hiv.bpca.samples.mcmclist,seq(1,1000,by=10))
hiv.bpca.xmat.gpa <- procGPA(hiv.bpca.xmat)
hiv.bpca.xmat.wgpa <- procWGPA(hiv.bpca.xmat,fixcovmatrix=FALSE,initial="Identity",maxiterations=100,scale=FALSE,prior="Exponential",diagonal=TRUE,sampleweights="Equal")
@ 

<<fig=TRUE>>=
patients <- unique(hiv.patients)
npatients <- length(patients)
plot(hiv.nocen.bmds.xmat.wgpa$mshape,type="n")
points(hiv.nocen.bmds.xmat.wgpa$mshape,col=as.integer(as.factor(hiv.patients)),pch=16)
for(i in 1:npatients){
  pt <- patients[i]
  rw <- hiv.patients%in%pt
  X <- hiv.nocen.bmds.xmat.wgpa$mshape[rw,1:2]
  hpts <- chull(X)
  hpts <- c(hpts, hpts[1])
  lines(X[hpts, ],col=i)
}
@ 

The colors aren't quite working out. Nevertheless, note the lack of clustering; however, this is the not censored version.

Need to fix such that variances are sorted?

<<fig=TRUE>>=
plot(hiv.bmds.xmat.wgpa$mshape,type="n")
text(hiv.bmds.xmat.wgpa$mshape,labels=hiv.names,col=as.integer(as.factor(hiv.patients)))
@ 

<<fig=TRUE>>=
plot(hiv.bpca.xmat.gpa$mshape,type="n")
text(hiv.bpca.xmat.gpa$mshape,labels=hiv.names,col=as.integer(as.factor(hiv.patients)))
@ 

Need to correlate antigenic distance with genetic distance.

<<fig=TRUE>>=
plot(hiv.bmds.samples.mcmclist$delta[1000,][[1]]~hiv.bmds.samples.mcmclist$d[1000,][[1]],xlab="d",ylab="delta",main="Normal")
abline(0,1,lty=3)
@ 

should calc correlation coefficient

\section{Comparison of ordinations} 

I compare the MDS solutions for the viruses visually. I rotate the ordinations so that the major variation is on the x axis.

<<calcpcarotations>>=
hiv.bmds.prcomp <- prcomp(hiv.bmds.xmat.wgpa$mshape,scale=FALSE,retx=TRUE)
@ 

Now I calculated the rotated matrices.

<<generaterotatedxmat>>=
hiv.bmds.xmat.wgpa.rot <- hiv.bmds.prcomp$x
@ 

Now I plot out the rotated ordinations.

<<ordmdsplot,fig=TRUE>>=
par(pty="s",font.lab=2)
plot(hiv.bmds.xmat.wgpa.rot,type="n",xlab="D1",ylab="D2",main="BMDS (normal prior)",xlim=c(-7,7),ylim=c(-0.6,0.6))
#text(x=hiv.bmds.xmat.wgpa.rot[1:23,1],y=hiv.bmds.xmat.wgpa.rot[1:36,2],labels=hiv.names[1:36],cex=0.75,col="blue")
points(x=hiv.bmds.xmat.wgpa.rot[1:60,1],y=hiv.bmds.xmat.wgpa.rot[1:60,2],pch=1,cex=0.75,col="blue")
text(x=hiv.bmds.xmat.wgpa.rot[61:76,1],y=hiv.bmds.xmat.wgpa.rot[61:76,2],labels=sera.names,cex=0.75,col="red")
@ 

The plasma and viruses cluster separately.

Now rotate all the MCMC runs. Look for convergence issues.

<<>>=
i <- 100
plot(hiv.bmds.xmat.wgpa$rotated[1:76,1:2,i]%*%hiv.bmds.prcomp$rotation)
@

Now rotate them all:

<<>>=
hiv.bmds.xmat.wgpa.rotated2 <- hiv.bmds.xmat.wgpa$rotated
for(i in 1:100){
hiv.bmds.xmat.wgpa.rotated2[1:76,1:2,i] <- hiv.bmds.xmat.wgpa$rotated[1:76,1:2,i]%*%hiv.bmds.prcomp$rotation
}
@

<<>>=
d <- as.data.frame(hiv.bmds.xmat.wgpa.rot) # this is the rotated mean shape
names(d) <- c("V1","V2")
d$V1 <- -d$V1 # so sera are more on right
d$V3 <- c(rep("Virus",60),rep("Sera",16)) # check
p <- ggplot(d,aes(x=V1,y=V2))+coord_fixed(ratio=1)
p <- p+scale_x_continuous(breaks=seq(-6,6),limits=c(-6,6))+scale_y_continuous(breaks=seq(-0.5,0.5),limits=c(-0.5,0.5))
p <- p+theme(axis.title.x = element_blank(),axis.title.y = element_blank(),legend.position="none",axis.text.x = element_blank(),axis.text.y = element_blank(),axis.ticks = element_blank())
for(i in 1:76){
  d1 <- as.data.frame(t(hiv.bmds.xmat.wgpa.rotated2[i,1:2,1:100]))
  d1$V1 <- -d1$V1
  p <- p + stat_density2d(data=d1,aes(x=V1,y=V2,fill=..level..),geom="polygon",alpha=0.01)
}
p <- p+geom_point(aes(colour=factor(V3)))+scale_colour_manual(values=c("blue","red"))
pdf("kircherrmap.pdf",width=10,height=2)
p+facet_grid(V3 ~ .)
dev.off()
@


Now save data.

<<>>=
save.image(file="kirchherr2.RData")
@ 


